version: '3'

services:
  twitter-analysis:
    build: .
    ports:
      - "8050:8050"
    volumes:
      - ./data:/app/data
      - ./visualizations:/app/visualizations
      - ./alerts:/app/alerts
    environment:
      - TWITTER_API_KEY=${TWITTER_API_KEY}
      - TWITTER_API_SECRET=${TWITTER_API_SECRET}
      - TWITTER_ACCESS_TOKEN=${TWITTER_ACCESS_TOKEN}
      - TWITTER_ACCESS_SECRET=${TWITTER_ACCESS_SECRET}
      - TWITTER_BEARER_TOKEN=${TWITTER_BEARER_TOKEN}
      - DEBUG=False
      - ALERT_THRESHOLD=10
      - ENGAGEMENT_THRESHOLD=100
      - SCAN_INTERVAL=300